version: "3.8"
services:
  app:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-your-org/trelax-core-backend}:${TAG:-latest}
    ports:
      - "6010:6010"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app-network

  auth-service:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-your-org/trelax-core-backend}/auth-service:${TAG:-latest}
    ports:
      - "6011:6011"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app-network

  chat-service:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-your-org/trelax-core-backend}/chat-service:${TAG:-latest}
    ports:
      - "6012:6012"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app-network

  cms-service:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-your-org/trelax-core-backend}/cms-service:${TAG:-latest}
    ports:
      - "6013:6013"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app-network

  crm-service:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-your-org/trelax-core-backend}/crm-service:${TAG:-latest}
    ports:
      - "6014:6014"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app-network

  notification-service:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-your-org/trelax-core-backend}/notification-service:${TAG:-latest}
    ports:
      - "6015:6015"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app-network

  project-service:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-your-org/trelax-core-backend}/project-service:${TAG:-latest}
    ports:
      - "6016:6016"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app-network

  property-service:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-your-org/trelax-core-backend}/property-service:${TAG:-latest}
    ports:
      - "6017:6017"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app-network

  user-service:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-your-org/trelax-core-backend}/user-service:${TAG:-latest}
    ports:
      - "6018:6018"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-prod
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
      - auth-service
      - chat-service
      - cms-service
      - crm-service
      - notification-service
      - project-service
      - property-service
      - user-service
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge 